apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-addition-config
  labels:
    app: addition-service
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  uvicorn-settings.json: |
    {
      "host": "0.0.0.0",
      "port": 8000,
      "log_level": "info",
      "reload": false,
      "workers": 2,
      "cors_origins": [
        {{- range .Values.cors.allowedOrigins }}
        "{{ . }}"{{- if ne . (last $.Values.cors.allowedOrigins) }},{{- end }}
        {{- end }}
      ]
    }