replicaCount: 1

image:
  repository: ghcr.io/dvirmoyal/calculator-java-service
  tag: latest
  pullPolicy: Always

environment: production

service:
  type: NodePort
  port: 8080
  nodePort: 30001

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

cors:
  allowedOrigins:
    - "http://calculator-microservices-frontend.s3-website-ap-southeast-1.amazonaws.com"