replicaCount: 1

image:
  repository: ghcr.io/dvirmoyal/python-calculator
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8000
  nodePort: 30000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

cors:
  allowedOrigins:
    - "http://calculator-microservices-frontend.s3-website-ap-southeast-1.amazonaws.com"